name: Publish CDN artifacts (canary) to S3
on:
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'carbon-design-system/carbon-for-ai'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          fetch-depth: '0'
      - uses: fkirc/skip-duplicate-actions@v5.3.1
        with:
          github_token: ${{ github.token }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8.9.2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build dist folders in each package
        run: pnpm build:dist:canary
      - name: Create one folder with dist contents from each package
        run: |
          mkdir dist
          cp -r packages/*/dist/. dist/
          ls dist
